[package]
name = "test-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sparse-merkle-tree = { path = "../sparse-merkle-tree" }
proptest = { version = "0.9"}

rand = "0.8"